# Generated by Django 5.2.4 on 2025-09-17 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='medicamentos',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='salario',
        ),
    ]
