# Generated by Django 5.2.6 on 2025-11-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("medico", "Médico"),
                    ("atendente", "Atendente"),
                    ("paciente", "Paciente"),
                    ("admin", "Admin"),
                ],
                max_length=20,
            ),
        ),
    ]
