# Generated by Django 5.2.6 on 2025-11-07 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_especialidade_alter_medico_especialidade"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="atendente",
            options={"verbose_name": "Atendente", "verbose_name_plural": "Atendentes"},
        ),
    ]
