# Generated by Django 5.2.6 on 2025-12-03 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
        ('core', '0006_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='data_hora_inicio',
            field=models.DateTimeField(default='2024-01-01 10:00', verbose_name='Início da Consulta'),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['data_hora_inicio'], 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.AlterUniqueTogether(
            name='consulta',
            unique_together={('medico', 'data_hora_inicio')},
        ),
        migrations.AddField(
            model_name='consulta',
            name='data_hora_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim da Consulta'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='lembrete_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas_medico', to='core.medico'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas_paciente', to='core.paciente'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='agendada', max_length=20),
        ),
        migrations.CreateModel(
            name='ExcecaoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(verbose_name='Início da Exceção')),
                ('data_fim', models.DateTimeField(verbose_name='Fim da Exceção')),
                ('esta_bloqueado', models.BooleanField(default=True, verbose_name='Bloquear Agenda?')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excecoes_horario', to='core.medico', verbose_name='Médico')),
            ],
            options={
                'verbose_name': 'Exceção de Horário/Ausência',
                'verbose_name_plural': 'Exceções de Horário/Ausências',
                'ordering': ['data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HorarioTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')], verbose_name='Dia da Semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Início')),
                ('hora_fim', models.TimeField(verbose_name='Hora de Fim')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_trabalho', to='core.medico', verbose_name='Médico')),
            ],
            options={
                'verbose_name': 'Horário de Trabalho Recorrente',
                'verbose_name_plural': 'Horários de Trabalho Recorrentes',
                'ordering': ['medico', 'dia_semana', 'hora_inicio'],
                'unique_together': {('medico', 'dia_semana', 'hora_inicio', 'hora_fim')},
            },
        ),
        migrations.DeleteModel(
            name='AvisoAusencia',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='data',
        ),
    ]
